@host= http://localhost:3001
@adminId= 653af742e010444afd03df99
@bikeId= 653ca73721618038231ea146
@bookingId= 653be3ccbe442efec2237287
### New Bike
POST {{host}}/api/bike/v1/
Content-Type: application/json

{
  "createdByAdminId": "{{adminId}}",
  "color": "#0000",
  "model": "Canyon Stumpjumper Evo Comp 2000",
  "description": "Offers is a great option that punches well above its weight on performance and price"
}

### Get Bike list
GET {{host}}/api/bike/v1/

### Get Bike
GET {{host}}/api/bike/v1/{{bikeId}}
