apiVersion: v1
kind: Service
metadata:
  name: booking
spec:
  selector:
    app: booking
  ports:
    - name: http
      port: 3000
      targetPort: booking-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking
  labels:
    app: booking
    layer: backend
    type: microservice
    name: bikers-community
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
  template:
    metadata:
      labels:
        app: booking
    spec:
      containers:
        - name: booking
          image: bikers-community/bookig:latest
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              memory: '250Mi'
              cpu: '500m'
            limits:
              memory: '250Mi'
              cpu: '500m'
          env:
            - name: PORT
              value: '3000'
            - name: BROKER_HOST
              value: 'localhost'
            - name: BROKER_PORT
              value: '5672'
            - name: DB_URL
              value: 'mongodb+srv://admin:admin@bikers-community.xhtftcd.mongodb.net/?retryWrites=true&w=majority'
            - name: DB_NAME
              value: 'booking'
            - name: DB_USER
              value: 'bikers-community'
            - name: DB_PASSWORD
              value: 'bikers-community'
            - name: DB_HOST
              value: 'localhost'
            - name: DB_PORT
              value: '27017'
