apiVersion: v1
kind: Service
metadata:
  name: notification
spec:
  selector:
    app: notification
  ports:
  - name: http
    port: 3000
    targetPort: notification-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  labels:
    app: notification
    layer: backend
    type: technical-service
    name: bikers-community
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
      - name: notification
        image: registry.hub.docker.com/jmvalenciz/bikers-community-notification:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "250Mi"
            cpu: "500m"
          limits:
            memory: "250Mi"
            cpu: "500m"
